{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Gijoe\\anaconda3\\lib\\site-packages\\pandas\\io\\sql.py:1423: UserWarning: The provided table name 'detailsCommande' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.\n",
      "  warnings.warn(msg, UserWarning)\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "from sqlalchemy import create_engine\n",
    "\n",
    "def run(filename):\n",
    "    engine = create_engine(\"mysql+pymysql://root:password@localhost:3306/foody3?charset=utf8\")\n",
    "    df = pd.read_csv(filename+\".csv\")\n",
    "    df.to_sql(name=filename,con=engine,if_exists='append',index=False)\n",
    "\n",
    "run('categorie')\n",
    "run('messager')\n",
    "run('client')\n",
    "run('fournisseur')\n",
    "run('employe') \n",
    "run('produit')\n",
    "run('commande')\n",
    "run('detailsCommande')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
